language: r

sudo: required

apt_packages:
 - libv8-dev
 
r_binary_packages:
 - rgdal

notifications:
  email:
    recipients:
     - tomaug@ceh.ac.uk
    on_success: change
    on_failure: change
  slack:
    secure: JSZ+rVXQEjfdNYqSm2N85WFc+LYnZg+6RFfa4o+MoCYQNGIVc6t+IIPFARL8ar+cdiP+Ih27Nv/hGk8fyvCtmVqJzmdK6A8Ey2xkXtL+xI4dTCNOVWCu7ald1vSZhvZYUL5O8mA9G5+XpDRPzyrMlaLkAEVtSoS4Ae8/OFlkmr0=
